id: IFDD28757
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:06:55+00:00'
last_modified: '2022-06-08T10:03:17.149462+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5818
  title: མཁར་རྡོ་རྗེ་འཆང་གི་རྣམ་ཐར་ངེས་དོན་བསྟན་པའི་མཛེས་རྒྱན་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    25CB:
      image_group_id: I1KG5841
      title: ''
      total_pages: 322
      order: 1
      base_file: 25CB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
